services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: backend
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app_network

  app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-Juanma-05.git
      dockerfile: dockerfile
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      - DATABASE_NAME=backend
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=mysqldb
    networks:
      - app_network

  frontend:
    build:
      context: https://github.com/etec-integration-project/first-tdd-Juanma-05.git
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - app_network

  nginx:
    build: https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-backend-Juanma-05/refs/heads/main/nginx/dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge